import Link from "next/link";
import { Instagram, Youtube } from "lucide-react";
import { T } from "@/components/language";
export function Footer(){return <footer className="border-t border-white/10 bg-[#0d0d0d]"><div className="container-main grid gap-10 py-14 md:grid-cols-[1.5fr_1fr_1fr_1fr]">
<div><Link href="/" className="display text-4xl font-bold">Rose<span className="text-rose">flix.</span></Link><p className="mt-4 max-w-xs text-sm leading-6 text-muted"><T en="Independent film criticism and discovery for curious movie lovers." tr="Meraklı sinemaseverler için bağımsız film eleştirileri ve keşif platformu."/></p></div>
<div><p className="eyebrow mb-4"><T en="Explore" tr="Keşfet"/></p><div className="grid gap-3"><Link className="text-sm text-muted hover:text-white" href="/reviews"><T en="Reviews" tr="İncelemeler"/></Link><Link className="text-sm text-muted hover:text-white" href="/categories"><T en="Categories" tr="Kategoriler"/></Link><Link className="text-sm text-muted hover:text-white" href="/blog"><T en="Journal" tr="Dergi"/></Link></div></div>
<div><p className="eyebrow mb-4"><T en="Company" tr="Roseflix"/></p><div className="grid gap-3"><Link className="text-sm text-muted hover:text-white" href="/about"><T en="About" tr="Hakkımızda"/></Link><Link className="text-sm text-muted hover:text-white" href="/contact"><T en="Contact" tr="İletişim"/></Link></div></div>
<div><p className="eyebrow mb-4"><T en="Follow the story" tr="Hikâyeyi takip et"/></p><div className="flex gap-3"><a aria-label="Instagram" className="border border-white/10 p-3 hover:border-rose" href="#"><Instagram size={18}/></a><a aria-label="Youtube" className="border border-white/10 p-3 hover:border-rose" href="#"><Youtube size={18}/></a></div></div>
</div><div className="container-main flex flex-col gap-2 border-t border-white/10 py-5 text-[11px] uppercase tracking-widest text-muted sm:flex-row sm:justify-between"><p>© 2026 Roseflix</p><p><T en="Made for people who stay through the credits." tr="Jenerik bitene kadar kalanlar için."/></p></div></footer>}
