import type { Metadata } from "next";
import Image from "next/image";
import { notFound } from "next/navigation";
import { Check, MessageCircle, Minus, Share2 } from "lucide-react";
import { movies, reviews, articles } from "@/data/content";
import { MovieCard, Score, SectionTitle } from "@/components/ui";
import { ArticleCard } from "@/components/article-card";

export function generateStaticParams(){return movies.map(m=>({slug:m.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params; const m=movies.find(x=>x.slug===slug); return {title:m?.title||"Movie",description:m?.synopsis,openGraph:{images:m?[m.backdrop]:[]}}}
export default async function MoviePage({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params; const movie=movies.find(m=>m.slug===slug); if(!movie)notFound(); const review=reviews.find(r=>r.movie.slug===slug)||reviews[0]; const similar=movies.filter(m=>m.slug!==slug&&m.genres.some(g=>movie.genres.includes(g))).slice(0,5);
 return <div>
  <section className="relative min-h-[68vh] overflow-hidden"><Image src={movie.backdrop} alt="" fill priority className="object-cover opacity-50"/><div className="absolute inset-0 bg-gradient-to-t from-ink via-ink/40 to-black/30"/><div className="container-main relative flex min-h-[68vh] items-end pb-12"><div className="grid w-full gap-7 md:grid-cols-[210px_1fr] md:items-end"><div className="relative hidden aspect-[2/3] overflow-hidden border border-white/20 shadow-2xl md:block"><Image src={movie.poster} alt="" fill className="object-cover"/></div><div><p className="eyebrow">Roseflix Review</p><h1 className="display mt-3 text-6xl font-semibold leading-[.9] md:text-8xl">{movie.title}</h1><div className="mt-5 flex flex-wrap items-center gap-3 text-xs text-white/70"><Score value={movie.rating} large/><span>{movie.year}</span><span>·</span><span>{movie.runtime}</span><span>·</span><span>{movie.genres.join(", ")}</span></div><p className="mt-5 max-w-2xl text-sm leading-7 text-white/70">{movie.synopsis}</p></div></div></div></section>
  <section className="container-main grid gap-12 py-16 lg:grid-cols-[1fr_280px]"><article><p className="eyebrow">Our take</p><h2 className="display mt-3 text-5xl font-semibold md:text-6xl">{movie.verdict}</h2><p className="mt-8 text-lg leading-9 text-white/80">{review.body}</p><p className="mt-6 text-base leading-8 text-muted">With a visual grammar built around negative space and carefully held close-ups, the film trusts the audience to notice what its characters cannot say. It is intimate filmmaking at an ambitious scale, and its final image lingers long after the credits.</p><div className="mt-10 grid gap-5 sm:grid-cols-2"><div className="border border-white/10 bg-panel p-6"><h3 className="text-sm font-extrabold uppercase tracking-widest text-blush">What works</h3>{review.pros.map(x=><p key={x} className="mt-4 flex gap-3 text-sm text-white/75"><Check className="mt-0.5 shrink-0 text-rose" size={16}/>{x}</p>)}</div><div className="border border-white/10 bg-panel p-6"><h3 className="text-sm font-extrabold uppercase tracking-widest text-muted">What doesn’t</h3>{review.cons.map(x=><p key={x} className="mt-4 flex gap-3 text-sm text-white/75"><Minus className="mt-0.5 shrink-0 text-muted" size={16}/>{x}</p>)}</div></div></article>
  <aside className="space-y-7 border-t border-white/10 pt-7 lg:border-l lg:border-t-0 lg:pl-7 lg:pt-0"><div><p className="eyebrow">Director</p><p className="mt-2 font-bold">{movie.director}</p></div><div><p className="eyebrow">Cast</p>{movie.cast.map(c=><p key={c} className="mt-2 text-sm text-muted">{c}</p>)}</div><div><p className="eyebrow">Roseflix score</p><p className="display mt-2 text-7xl font-semibold">{movie.rating}<span className="text-2xl text-muted">/10</span></p></div><button className="flex w-full items-center justify-center gap-2 border border-white/15 py-3 text-xs font-bold uppercase tracking-widest hover:border-rose"><Share2 size={14}/>Share review</button></aside></section>
  <section className="bg-panel py-16"><div className="container-main"><SectionTitle eyebrow="Keep Watching" title="Similar Movies"/><div className="grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-5">{similar.map((m,i)=><MovieCard key={m.slug} movie={m} index={i}/>)}</div></div></section>
  <section className="container-main py-16"><SectionTitle eyebrow="Community" title="Audience Notes"/><div className="grid gap-4 md:grid-cols-2">{["The ending completely reframed the first act for me. Quietly devastating.","That sound design deserves to be experienced in a theater."].map((x,i)=><div key={x} className="border border-white/10 p-6"><MessageCircle size={18} className="text-rose"/><p className="mt-4 text-sm leading-7 text-white/80">“{x}”</p><p className="mt-5 text-[10px] font-extrabold uppercase tracking-widest text-muted">@filmlover{i+4}</p></div>)}</div></section>
  <section className="container-main pb-20"><SectionTitle eyebrow="Go Deeper" title="Related Stories"/><div className="grid gap-7 md:grid-cols-3">{articles.slice(0,3).map(a=><ArticleCard key={a.slug} article={a}/>)}</div></section>
 </div>
}
